    // display(first);
    // printf("\n");
    // displayRecursive(first);
    // printf("\n");
    // printf("count is %d\n", Count(first));
    // printf("sum is : %d\n", Sum(first));
    // printf("max is : %d\n", Max(first));
    // printf("min is : %d\n", Min(first));
    // struct Node *temp = SearchR(first, 3);
    // printf("Key found %d  at address %d \n", temp->value, temp);